### ISSUE TITLE
Public access to a child account

### ISSUE THREAD

**Issue by ka8725** [widefix/pocketmoney#35]
As a parent, I want to share my child's account. There should be generated a public URL that's accessible by everyone.
When I create a share I specify for how long the link is active: 15 min, 30 min, 1h, 1 day, 1 week, 1 month, or forever.
I should be able to delete a share later.

**Comment by ka8725** [comment]
Basic scenario: without the active period.

Advanced scenario: with

Implement only without for now.

**Comment by ka8725** [comment]
It's reproduced like this:

I'm as the child account parent share the public.

**Comment by ka8725** [comment]
this area should be removed



![Image](https://github.com/widefix/pocketmoney/assets/243846/193440f6-197e-4e37-aa2b-9ad086031ef3)

**Comment by ka8725** [comment]
Also I get this on a shared account in prod:

```
2023-09-06T16:25:06.168959014Z app[web.1]: I, [2023-09-06T16:25:06.168871 #12]  INFO -- : [2c2ee69a-34af-4ed4-a83c-fc8916a35d85] Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.0ms | Allocations: 1043)
2023-09-06T16:25:06.169828613Z app[web.1]: F, [2023-09-06T16:25:06.169724 #12] FATAL -- : [2c2ee69a-34af-4ed4-a83c-fc8916a35d85]
2023-09-06T16:25:06.169855142Z app[web.1]: [2c2ee69a-34af-4ed4-a83c-fc8916a35d85] ActionView::Template::Error (undefined method `account_id' for nil:NilClass):
2023-09-06T16:25:06.169860488Z app[web.1]: [2c2ee69a-34af-4ed4-a83c-fc8916a35d85]     2:   | Account details
2023-09-06T16:25:06.169864902Z app[web.1]: [2c2ee69a-34af-4ed4-a83c-fc8916a35d85]     3: .buttons
2023-09-06T16:25:06.169869458Z app[web.1]: [2c2ee69a-34af-4ed4-a83c-fc8916a35d85]     4:   = link_to 'Back', my_account_path, class: 'button is-light'
2023-09-06T16:25:06.169873975Z app[web.1]: [2c2ee69a-34af-4ed4-a83c-fc8916a35d85]     5:   - unless public_share?(account)
2023-09-06T16:25:06.169878341Z app[web.1]: [2c2ee69a-34af-4ed4-a83c-fc8916a35d85]     6:     = link_to 'Edit', edit_account_path(account), class: 'button is-light'
2023-09-06T16:25:06.169882948Z app[web.1]: [2c2ee69a-34af-4ed4-a83c-fc8916a35d85]     7:     = link_to 'Account shares', account_shares_path(account), class: 'button is-light'
2023-09-06T16:25:06.169887448Z app[web.1]: [2c2ee69a-34af-4ed4-a83c-fc8916a35d85]     8: .columns
2023-09-06T16:25:06.169919809Z app[web.1]: [2c2ee69a-34af-4ed4-a83c-fc8916a35d85]
2023-09-06T16:25:06.169924415Z app[web.1]: [2c2ee69a-34af-4ed4-a83c-fc8916a35d85] app/models/account.rb:20:in `block in <class:Account>'
2023-09-06T16:25:06.169929159Z app[web.1]: [2c2ee69a-34af-4ed4-a83c-fc8916a35d85] app/controllers/accounts_controller.rb:35:in `account'
2023-09-06T16:25:06.169933638Z app[web.1]: [2c2ee69a-34af-4ed4-a83c-fc8916a35d85] app/controllers/accounts_controller.rb:35:in `account'
2023-09-06T16:25:06.169938052Z app[web.1]: [2c2ee69a-34af-4ed4-a83c-fc8916a35d85] app/views/accounts/show.html.slim:5
```
